### ISSUE TITLE
Use configuration files to handle storage strategies.

### ISSUE THREAD

**Issue by bmschmidt** [massivetexts/htrc-feature-reader#13]
Slightly big, but let me work backwards here because I'm hammering you about defaults without stepping back to explain what I'd really like to see. And I think it's probably user-centered configuration. This is what we've stumbled to in massive texts, and I wonder if it wouldn't mostly solve this mess of issues I'm raising and make code using this module more portable to boot.

# Goals

To allow people to distribute code using this module that will use a customized storage backend but perform similarly. Currently, I only describe something called 'id_search_strategy'; I just leave other slots open in case. (One logical thing to include might be 'ef-version.')

Here are the basic ideas:

1. Beginners should be heavily steered into identifying features by ids, rather than filepaths. Once they do that, code becomes much more portable. And they probably shouldn't have to think very much about where those ids come from.
2. Everyone is going to have different preferred ways of storing on different machines. @organisciak likes to keep his parquets and json.bz2s in different file trees, I like to keep them in the same one.
3. Shared code using this module shouldn't necessarily have to have a folder with megabytes of json.bz2 files in it.

# Sensible defaults

Currently, if you pass 'id' with no arguments, it will hit HTRC again and again. This is bad.

So we can use a default configuration that does the following:

1. Looks in a folder called 'htrc-features/' using pairtree. (Or not pairtree, up to you.)
2. Pulls the id over http (what role could rsync play?), and writes the json.gz file to that pairtree loc if it doesn't exist.

# Configuration Files

I want to have a file called `htrc_config.yml` that we read on startup to store user-specific details about how to locate an ID or list of ids. 

In general, with this sort of config file, it should exist at two places. One is the present working directory; another is some set of global locations (probably '~/.htrc_features_config.yml')

Mine might look like this:

```yml
override_code_id_strategies: true
id_search_strategy:
  - 
     format: parquet
     location: pairtree
     create_if_not_present: true
     dir: "/drobo/ht-features-parquet"
     compression: snappy
     indexed: false
  - 
     format: json
     location: local
     compression: bz2
     create_if_not_present: false
     dir: "features"
  - 
     format: json
     location: https
     endpoint: 'f"http://data.htrc.illinois.edu/htrc-ef-access/get?action=download-ids&id={id}&output={format}"'

```
